module.exports = {
  MAX_FILE_SIZE: process.env.MAX_FILE_SIZE || 1024 * 1024 * 10,
  UPLOAD_PATH: process.env.UPLOAD_PATH || '/tmp/uploads/',
  MAX_NUM_UPLOADS: process.env.MAX_NUM_UPLOADS || 20,
  MONGO_URI: process.env.MONGO_URI,
  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
  SIGNING_KEY: process.env.SIGNING_KEY,
  RECAPTCHA_ENABLED: !!(process.env.RECAPTCHA_SITE_KEY && process.env.RECAPTCHA_SECRET_KEY),
  RECAPTCHA_SITE_KEY: process.env.RECAPTCHA_SITE_KEY,
  RECAPTCHA_SECRET_KEY: process.env.RECAPTCHA_SECRET_KEY,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  AWS_BUCKET_NAME: process.env.AWS_BUCKET_NAME,
  S3_BUCKET_ENABLED = process.env.S3_BUCKET_ENABLED === "true"

};
